sudo: false
cache:
  directories:
  - $HOME/.gradle/wrapper
language: groovy
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
jdk:
  - oraclejdk8
script: ./script/cibuild
# after_failure: ./travis/junit-errors-to-stdout.sh
